import React from 'react';
import SurveyInfo from 'src/components/SurveyInfo';
import QuestionGender from 'src/components/QuestionGender'; 
import QuestionAge from 'src/components/QuestionAge';
import QuestionCelebrate from 'src/components/QuestionCelebrate.jsx';
import QuestionLikeMost from 'src/components/QuestionLikeMost'; 
import QuestionGift from 'src/components/QuestionGift';
import Submit from 'src/components/Submit'; 
import Footer from 'src/components/Footer';